title: Alexey Nikitin
email: nikialeksey@gmail.com
description: >
  Blog about Java programming, clean code and Android development
lang: ru_RU
baseurl: ""
url: "https://www.nikialeksey.com"
excerpt_separator: <!--more-->
paginate: 4
paginate_path: "/page-:num/"

twitter_username: nikialeksey
github_username:  nikialeksey
linkedin_username: nikialeksey

twitter:
  username: nikialeksey
social:
  name: Alexey Niktin
  links:
    - https://twitter.com/nikialeksey
    - https://github.com/nikialeksey
google_analytics: UA-96573346-1
disqus:
    shortname: nikialeksey-blog

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
